name: 02 - Workflow Events

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 8 13 5 1'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "The event name that triggered the workflow is: ${{ github.event_name }}"
